### ISSUE TITLE
scala-3.0.0.4 2 does not compile on Mac OS Catalina 10.15.13

### ISSUE THREAD

**Issue by beugelpp** [scala-network/scala-v7#65]
64%] Building CXX object src/checkpoints/CMakeFiles/obj_checkpoints.dir/checkpoints.cpp.o
/Users/rene/Downloads/Scala-3.0.0.4 2/src/checkpoints/checkpoints.cpp:315:41: error: unknown type name
      'scala_dir_usable'
                        std::ofstream o(scala_dir_usable);
                                        ^
/Users/rene/Downloads/Scala-3.0.0.4 2/src/checkpoints/checkpoints.cpp:315:40: warning: parentheses were disambiguated
      as a function declaration [-Wvexing-parse]
                        std::ofstream o(scala_dir_usable);
                                       ^~~~~~~~~~~~~~~~~~
/Users/rene/Downloads/Scala-3.0.0.4 2/src/checkpoints/checkpoints.cpp:315:41: note: add a pair of parentheses to
      declare a variable
                        std::ofstream o(scala_dir_usable);
                                        ^
                                        (
/Users/rene/Downloads/Scala-3.0.0.4 2/src/checkpoints/checkpoints.cpp:393:22: error: unknown type name
      'scala_dir_usable'
    std::ofstream o2(scala_dir_usable);
                     ^
/Users/rene/Downloads/Scala-3.0.0.4 2/src/checkpoints/checkpoints.cpp:393:21: warning: parentheses were disambiguated
      as a function declaration [-Wvexing-parse]
    std::ofstream o2(scala_dir_usable);
                    ^~~~~~~~~~~~~~~~~~
/Users/rene/Downloads/Scala-3.0.0.4 2/src/checkpoints/checkpoints.cpp:393:22: note: add a pair of parentheses to
      declare a variable
    std::ofstream o2(scala_dir_usable);
